name: HTML Validator

on:
  push:
    branches:
      - master

jobs:
  html-validator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install html-validator-cli
        run: npm install -g html-validator-cli

      - name: Run HTML Validation
        run: html-validator index.html --verbose

